=== bcandido/summer_project/script/descriptor.dtd
<!-- ELEMENT LIST -->
<!ELEMENT taskrunner (plugin*)>
<!ELEMENT plugin (description*, taskList)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT taskList (task*)>
<!ELEMENT task (description*, command)>
<!ELEMENT command (#PCDATA)>

<!-- ATTRIBUTE LIST -->
<!ATTLIST plugin name #PCDATA #REQUIRED>

=== bcandido/summer_project/script/descriptor.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE taskrunner SYSTEM "descriptor.dtd">
<taskrunner>
	<plugin name="shell">
<!-- 		<description> This plugin executes shell commands </description> -->
		<taskList>
			<!--<task>
				<description> displays files in the directory </description>
				<command> ls </command>
			</task>-->
			<task>
				<description> show the processes running </description>
				<command>ls | grep wc -l</command>
			</task>
			<task>
				<description> displays files in the directory </description>
				<command> ls %PATH -al </command>
			</task>
		</taskList>
	</plugin>
	<plugin name="smtp">
		<description> This plugin executes shell commands </description>
		<taskList>
			<task>
				<description> home path </description>
				<command> ls -l </command>
			</task>
		</taskList>
	</plugin>
</taskrunner>
